#!/usr/bin/python

import os, shutil

src_bim = "./TabularProject/TabularProject/Model.bim"
model_folder = os.getcwd()
tabular_editor_path = "D:/LongVDH/TabularEditor.Portable.2.16.3/TabularEditor.exe"


# Convert merged folder into semantic model (.bim file)
# This should be done because git also handle merge changes automatically
print("Start serializing into Model.bim...")
os.system(f'cmd /c \
    ""{tabular_editor_path}" "{model_folder}" \
    -S ApplySerializeOptionsAnnotation.csx \
    -B Model.bim"')


# Copy converted .bim to Visual Studio project folder (replace old file)
print("Complete serialize, copy Model.bim to VS Project")
if os.path.exists(src_bim):
    os.remove(src_bim)
shutil.copy("Model.bim", os.path.dirname(src_bim))